package Config;
import Config.KoneksiDb;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TabelPenyewa extends javax.swing.JFrame {

    private static void setModel(DefaultTableModel model) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public TabelPenyewa() {
        initComponents();
        tampilkan_data();
        isianbersih();
    }


    public void isianbersih(){
    txtkodepenyewa.setText("");
    txtnama.setText("");
    txtalamat.setText("");
    txttelepon.setText("");
 
}
    public void tampilkan_data(){
        DefaultTableModel model = new  DefaultTableModel();
       
        model.addColumn("Kode Penyewa");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Nomor Telepon");
        
        String cari = txtCari.getText();
        try{
            String sql ="Select * From tb_penyewa where kd_penyewa LIKE'%"+cari+"%'";
            KoneksiDb koneksi = new KoneksiDb();
            java.sql.Connection con = koneksi.getConnection(); 
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            
            
            while (res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
            
                TabelPenyewa.setModel(model);
            }
            
        }catch(SQLException e){
            System.out.println("ERROR :" +e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bTambah = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bBatal = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bTutup = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtkodepenyewa = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bTutup2 = new javax.swing.JButton();
        bHapus2 = new javax.swing.JButton();
        bBatal2 = new javax.swing.JButton();
        bUbah2 = new javax.swing.JButton();
        bTambah2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPenyewa = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        bCari = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        bTambah.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bUbah.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bBatal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bBatal.setText("Batal");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        bHapus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bTutup.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bTutup.setText("Tutup");
        bTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTutupActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kode Penyewa");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("No Telpon");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Alamat");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama");

        bTutup2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bTutup2.setText("Tutup");
        bTutup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTutup2ActionPerformed(evt);
            }
        });

        bHapus2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bHapus2.setText("Hapus");
        bHapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapus2ActionPerformed(evt);
            }
        });

        bBatal2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bBatal2.setText("Batal");
        bBatal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatal2ActionPerformed(evt);
            }
        });

        bUbah2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bUbah2.setText("Ubah");
        bUbah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbah2ActionPerformed(evt);
            }
        });

        bTambah2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bTambah2.setText("Tambah");
        bTambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambah2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bTambah2)
                .addGap(18, 18, 18)
                .addComponent(bUbah2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bBatal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bHapus2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bTutup2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBatal2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUbah2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTambah2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHapus2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTutup2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtkodepenyewa, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtalamat)
                    .addComponent(txttelepon))
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtkodepenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        TabelPenyewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelPenyewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPenyewaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelPenyewa);

        bCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bCari.setText("Cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Cari");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bCari, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(102, 255, 102));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("DATA PENYEWA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(130, 130, 130))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        if (txtkodepenyewa.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Kode Penyewa Belum diisi");
            txtkodepenyewa.requestFocus();
        }else if (txtnama.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Nama Belum diisi");
            txtnama.requestFocus();
        }else if(txtalamat.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Alamat Belum diisi");
            txtalamat.requestFocus();
        }else if (txttelepon.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Nomor Telepon Belum diisi");
            txttelepon.requestFocus();
        }else{
            try{
                String sql ="INSERT INTO tb_penyewa VALUES ('" + txtkodepenyewa.getText() + "','" + txtnama.getText() + "','" + txtalamat.getText() + "','" + txttelepon.getText() + "')";
                KoneksiDb koneksi = new KoneksiDb();
                Connection con = koneksi.getConnection();
                PreparedStatement pst = con.prepareStatement(sql);
                pst.execute();
                tampilkan_data();

                JOptionPane.showMessageDialog(null, "Berhasil Menyimpan");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Gagal Menyimpan" + e.getMessage());

    }//GEN-LAST:event_bTambahActionPerformed
        }}
    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Untuk Ubah Data Ini???","Confirmation",JOptionPane.YES_NO_OPTION);
        try
        {
            String sql="update tb_penyewa set kodepenyewa=?,nama=?,alamat=?,telepon=? where kodepenyewa='"+txtkodepenyewa.getText()+"'";
            Connection con=new KoneksiDb().getConnection();
            PreparedStatement pst = con.prepareStatement(sql);

            if(ok==0)
            {
                try
                {
                    pst.setString(1,txtkodepenyewa.getText());
                    pst.setString(2,txtnama.getText());
                    pst.setString(3,txtalamat.getText());
                    pst.setString(4,txttelepon.getText());
                    pst.executeUpdate();
                    tampilkan_data();

                    JOptionPane.showMessageDialog(null,"Ubah Data Berhasil");
                }catch (Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Ubah Data Gagal");
                }
            }
        }catch (Exception e){}
    }//GEN-LAST:event_bUbahActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        isianbersih();
    }//GEN-LAST:event_bBatalActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        String kodepenyewa,nama,alamat,telepon;
        try{
            kodepenyewa=txtkodepenyewa.getText().trim();
            nama=txtnama.getText().trim();
            alamat=txtalamat.getText().trim();
            telepon=txttelepon.getText().trim();
            Connection con=new KoneksiDb().getConnection();
            Statement st=con.createStatement();
            String sql="delete from tb_penyewa where kodepenyewa='"+kodepenyewa+"';";
            st.execute(sql);
            st.close();
            JOptionPane.showMessageDialog(this, "Data berhasil di hapus");
            tampilkan_data();
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Data gagal di hapus"+e);
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTutupActionPerformed
        dispose();
    }//GEN-LAST:event_bTutupActionPerformed

    private void bTambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambah2ActionPerformed
        if (txtkodepenyewa.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Kode Penyewa Belum diisi");
            txtkodepenyewa.requestFocus();
        }else if (txtnama.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Nama Belum diisi");
            txtnama.requestFocus();
        }else if(txtalamat.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Alamat Belum diisi");
            txtalamat.requestFocus();
        }else if (txttelepon.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Nomor Telepon Belum diisi");
            txttelepon.requestFocus();
        }else{
            try{
                String sql ="INSERT INTO tb_penyewa VALUES ('" + txtkodepenyewa.getText() + "','" + txtnama.getText() + "','" + txtalamat.getText() + "','" + txttelepon.getText() + "')";
                KoneksiDb koneksi = new KoneksiDb();
                Connection con = koneksi.getConnection();
                PreparedStatement pst = con.prepareStatement(sql);
                pst.execute();
                tampilkan_data();

                JOptionPane.showMessageDialog(null, "Berhasil Menyimpan");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Gagal Menyimpan" + e.getMessage());

    }//GEN-LAST:event_bTambah2ActionPerformed
        }}
    private void bUbah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbah2ActionPerformed
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Untuk Ubah Data Ini???","Confirmation",JOptionPane.YES_NO_OPTION);
        try
        {
            String sql="update tb_penyewa set kodepenyewa=?,nama=?,alamat=?,telepon=? where kodepenyewa='"+txtkodepenyewa.getText()+"'";
            Connection con=new KoneksiDb().getConnection();
            PreparedStatement pst = con.prepareStatement(sql);

            if(ok==0)
            {
                try
                {
                    pst.setString(1,txtkodepenyewa.getText());
                    pst.setString(2,txtnama.getText());
                    pst.setString(3,txtalamat.getText());
                    pst.setString(4,txttelepon.getText());
                    pst.executeUpdate();
                    tampilkan_data();

                    JOptionPane.showMessageDialog(null,"Ubah Data Berhasil");
                }catch (Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Ubah Data Gagal");
                }
            }
        }catch (Exception e){}
    }//GEN-LAST:event_bUbah2ActionPerformed

    private void bHapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapus2ActionPerformed
        String kodepenyewa,nama,alamat,telepon;
        try{
            kodepenyewa=txtkodepenyewa.getText().trim();
            nama=txtnama.getText().trim();
            alamat=txtalamat.getText().trim();
            telepon=txttelepon.getText().trim();
            Connection con=new KoneksiDb().getConnection();
            Statement st=con.createStatement();
            String sql="delete from tb_penyewa where kodepenyewa='"+kodepenyewa+"';";
            st.execute(sql);
            st.close();
            JOptionPane.showMessageDialog(this, "Data berhasil di hapus");
            tampilkan_data();
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Data gagal di hapus"+e);
        }
    }//GEN-LAST:event_bHapus2ActionPerformed

    private void bBatal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatal2ActionPerformed
        isianbersih();
    }//GEN-LAST:event_bBatal2ActionPerformed

    private void bTutup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTutup2ActionPerformed
        dispose();
    }//GEN-LAST:event_bTutup2ActionPerformed

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        tampilkan_data();
    }//GEN-LAST:event_bCariActionPerformed

    private void TabelPenyewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPenyewaMouseClicked

        int baris = TabelPenyewa.rowAtPoint(evt.getPoint());
        String kode = TabelPenyewa.getValueAt(baris, 0).toString();
        txtkodepenyewa.setText(kode);
        String nama = TabelPenyewa.getValueAt(baris, 1).toString();
        txtnama.setText(nama);
        String alamat = TabelPenyewa.getValueAt(baris, 2).toString();
        txtalamat.setText(alamat);
        String telepon = TabelPenyewa.getValueAt(baris, 3).toString();
        txttelepon.setText(telepon);
    }//GEN-LAST:event_TabelPenyewaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelPenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelPenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelPenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelPenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelPenyewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelPenyewa;
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bBatal2;
    private javax.swing.JButton bCari;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bHapus2;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bTambah2;
    private javax.swing.JButton bTutup;
    private javax.swing.JButton bTutup2;
    private javax.swing.JButton bUbah;
    private javax.swing.JButton bUbah2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtkodepenyewa;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables
}
